### ISSUE TITLE
When scanning barcodes it doesn't work

### ISSUE THREAD

**Issue by atodorov** [AnetaStoycheva/QA-and-Automation-101#2]
<br /> **Summary (about 10 words):** Wrong name of Facebook App icon on Adroid phone
<br />_Description:_
<br />**Version of the System:** 123
<br />**Version of the OS:** 456
<br />**Version of the Device:** 789
<br />_Preconditions:_
<br />**Steps to Reproduce:**
<br />**Actual (observed) Result:** The text under the Facebook icon on Android phone is not correct.
It is supposed to be "Facebook", but now is "false".
<br />**Expected Result:**
<br />_How often it is reproducible:_
<br />_Additional Information (screenshots, urls, etc.):_
<br />**Priority:**
<br />_Assign to:_
<br />_Found by:_
<br />_Fond on Date:_
<br />How it Affects Clients:
<br />Proposals to fix the bug:

**Comment by AnetaStoycheva** [comment]
Exercising in class.
